services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    user: www-data

  nginx-back:
    image: nginx:alpine
    container_name: nginx-back
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
